apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-71uh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-71uh
    app.kubernetes.io/part-of: ci10t-777-0046-app
  name: devfile-sample-71uh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-71uh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-71uh
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0046-tenant/ci10t-777-0046-app/devfile-sample-71uh@sha256:023e560288afb12747b67a6f9f3a16209dbf5e153d4abc9b7f43e44fbae60b88
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
